### ISSUE TITLE
error when trying to run the app for a first time: app crashing

### ISSUE THREAD

**Issue by marrie** [dtube/dtube#66]
I'm quite new at the compile thing but I did follow the directions in the read me. I get a log that says the app is crashing. I'm running this on mac os 10.13.6 on a mac book  air. I changed to the directory where the dtube thign is and that's when the trouble started when I tried to run the app, or at least try and minify the files. Here is the log in full

/Users/sa/dtubeapp/dtube/.meteor/local/build/programs/server/boot.js:475
}).run();
   ^

Error: Cannot find module '@babel/runtime/helpers/builtin/interopRequireDefault'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.resolve (internal/module.js:18:19)
    at Object.require (/Users/sa/dtubeapp/dtube/.meteor/local/build/programs/server/boot.js:288:32)
    at makeInstallerOptions.fallback (packages/modules-runtime.js:653:18)
    at require (packages/modules-runtime.js:244:16)
    at livedata_connection.js (/Users/sa/dtubeapp/dtube/.meteor/local/build/programs/server/packages/ddp-client.js:147:30)
    at fileEvaluate (packages/modules-runtime.js:339:7)
    at require (packages/modules-runtime.js:238:16)
    at namespace.js (packages/ddp-client/common/namespace.js:1:300)
    at fileEvaluate (packages/modules-runtime.js:339:7)
Exited with code: 1
Your application is crashing. Waiting for file change.
I hope that helps a bit. And thanks.

**Comment by techcoderx** [comment]
The latest version compiles on nodejs v14.9 and the latest Meteor. Closing this for now, if the issue still persists please reopen
